language: cpp

# sudo: required

os:
# - osx
- linux

compiler:
- gcc
- clang

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake', 'debian-sid']
    packages: ['clang-3.7', 'cmake', 'qt5-default']

env: COMPILER=clang++-3.7

# matrix:
#   exclude:
#     - os: osx
#       compiler: gcc

notifications:
  email: 
    - joerg.preiss@slesa.de

# before_install:
# - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
# - sudo apt-get update -qq
# - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev

before_script:
- mkdir src/build
- cd src/build
- cmake ..

script: make

after_success:
- ctest -V --output-on-failure 
- cpack
