language: cpp

# sudo: required

os:
# - osx
- linux

compiler:
- gcc
- clang

#addons:
#  apt:
#    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake']
#    sources: ['debian-sid']
#    packages: 
#	- cmake
#	- -qt5-default

# env: COMPILER=clang++-3.7

# matrix:
#   exclude:
#     - os: osx
#       compiler: gcc

notifications:
  email: 
    - joerg.preiss@slesa.de

before_install:
- sudo add-apt-repository --yes ppa:george-edison55/precise-backports
- sudo add-apt-repository --yes ppa:beineri/opt-qt562
- sudo apt-get update -qq
- sudo apt-get install cmake qt56base qt56svg qt56translations qt56x11extras

before_script:
- mkdir src/build
- cd src/build
- cmake ..

script: make

after_success:
- ctest -V --output-on-failure 
- cpack
